### ISSUE TITLE
The given key 'false' was not present in the dictionary

### ISSUE THREAD

**Issue by Maverick1983** [dnSpyEx/dnSpy#144]
- What version did you use?
last

I open a Form and I see this:

`System.AggregateException: One or more errors occurred. (The given key 'false' was not present in the dictionary.)
 ---> System.Collections.Generic.KeyNotFoundException: The given key 'false' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at ICSharpCode.NRefactory.CSharp.Resolver.ResolveVisitor.GetResolveResult(AstNode node) in D:\a\dnSpyEx\dnSpyEx\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Resolver\ResolveVisitor.cs:line 462
   at ICSharpCode.NRefactory.CSharp.Resolver.CSharpAstResolver.Resolve(AstNode node, CancellationToken cancellationToken) in D:\a\dnSpyEx\dnSpyEx\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Resolver\CSharpAstResolver.cs:line 167
   at ICSharpCode.NRefactory.CSharp.Analysis.ControlFlowGraphBuilder.EvaluateConstant(Expression expr) in D:\a\dnSpyEx\dnSpyEx\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Analysis\ControlFlow.cs:line 304
   at ICSharpCode.NRefactory.CSharp.Analysis.ControlFlowGraphBuilder.EvaluateCondition(Expression expr) in D:\a\dnSpyEx\dnSpyEx\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Analysis\ControlFlow.cs:line 313
   at ICSharpCode.NRefactory.CSharp.Analysis.ControlFlowGraphBuilder.NodeCreationVisitor.VisitDoWhileStatement(DoWhileStatement doWhileStatement, ControlFlowNode data) in D:\a\dnSpyEx\dnSpyEx\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Analysis\ControlFlow.cs:line 569
   at ICSharpCode.NRefactory.CSharp.DoWhileStatement.AcceptVisitor[T,S](IAstVisitor`2 visitor, T data) in D:\a\dnSpyEx\dnSpyEx\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\Statements\DoWhileStatement.cs:line 79
   at ICSharpCode.NRefactory.CSharp.Analysis.ControlFlowGraphBuilder.NodeCreationVisitor.HandleStatementList(AstNodeCollection`1 statements, ControlFlowNode source) in D:\a\dnSpyEx\dnSpyEx\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Analysis\ControlFlow.cs:line 383
   at ICSharpCode.NRefactory.CSharp.Analysis.ControlFlowGraphBuilder.NodeCreationVisitor.VisitBlockStatement(BlockStatement blockStatement, ControlFlowNode data) in D:\a\dnSpyEx\dnSpyEx\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Analysis\ControlFlow.cs:line 369
   at ICSharpCode.NRefactory.CSharp.BlockStatement.AcceptVisitor[T,S](IAstVisitor`2 visitor, T data) in D:\a\dnSpyEx\dnSpyEx\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\Statements\BlockStatement.cs:line 143
   at ICSharpCode.NRefactory.CSharp.Analysis.ControlFlowGraphBuilder.BuildControlFlowGraph(Statement statement, Func`3 resolver, CSharpTypeResolveContext typeResolveContext, CancellationToken cancellationToken) in D:\a\dnSpyEx\dnSpyEx\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Analysis\ControlFlow.cs:line 197
   at ICSharpCode.NRefactory.CSharp.Analysis.ControlFlowGraphBuilder.BuildControlFlowGraph(Statement statement, CSharpAstResolver resolver, CancellationToken cancellationToken) in D:\a\dnSpyEx\dnSpyEx\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Analysis\ControlFlow.cs:line 180
   at ICSharpCode.NRefactory.CSharp.Analysis.DefiniteAssignmentAnalysis.InsertAnonymousMethods(Int32 insertPos, AstNode node, ControlFlowGraphBuilder cfgBuilder, CancellationToken cancellationToken) in D:\a\dnSpyEx\dnSpyEx\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Analysis\DefiniteAssignmentAnalysis.cs:line 153
   at ICSharpCode.NRefactory.CSharp.Analysis.DefiniteAssignmentAnalysis.InsertAnonymousMethods(Int32 insertPos, AstNode node, ControlFlowGraphBuilder cfgBuilder, CancellationToken cancellationToken) in D:\a\dnSpyEx\dnSpyEx\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Analysis\DefiniteAssignmentAnalysis.cs:line 164
   at ICSharpCode.NRefactory.CSharp.Analysis.DefiniteAssignmentAnalysis..ctor(Statement rootStatement, CSharpAstResolver resolver, CancellationToken cancellationToken) in D:\a\dnSpyEx\dnSpyEx\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\Analysis\DefiniteAssignmentAnalysis.cs:line 125
   at ICSharpCode.Decompiler.Ast.Transforms.DeclareVariables.Run(AstNode node, DefiniteAssignmentAnalysis daa) in D:\a\dnSpyEx\dnSpyEx\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\DeclareVariables.cs:line 114
   at ICSharpCode.Decompiler.Ast.Transforms.DeclareVariables.Run(AstNode node, DefiniteAssignmentAnalysis daa) in D:\a\dnSpyEx\dnSpyEx\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\DeclareVariables.cs:line 138
   at ICSharpCode.Decompiler.Ast.Transforms.DeclareVariables.Run(AstNode node, DefiniteAssignmentAnalysis daa) in D:\a\dnSpyEx\dnSpyEx\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\DeclareVariables.cs:line 138
   at ICSharpCode.Decompiler.Ast.Transforms.DeclareVariables.Run(AstNode node, DefiniteAssignmentAnalysis daa) in D:\a\dnSpyEx\dnSpyEx\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\DeclareVariables.cs:line 138
   at ICSharpCode.Decompiler.Ast.Transforms.DeclareVariables.Run(AstNode node, DefiniteAssignmentAnalysis daa) in D:\a\dnSpyEx\dnSpyEx\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\DeclareVariables.cs:line 138
   at ICSharpCode.Decompiler.Ast.Transforms.DeclareVariables.Run(AstNode node) in D:\a\dnSpyEx\dnSpyEx\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\DeclareVariables.cs:line 64
   at ICSharpCode.Decompiler.Ast.Transforms.TransformationPipeline.RunTransformationsUntil(AstNode node, Predicate`1 abortCondition, DecompilerContext context) in D:\a\dnSpyEx\dnSpyEx\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\Transforms\TransformationPipeline.cs:line 67
   at ICSharpCode.Decompiler.Ast.AstBuilder.RunTransformations(Predicate`1 transformAbortCondition) in D:\a\dnSpyEx\dnSpyEx\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstBuilder.cs:line 314
   at dnSpy.Decompiler.ILSpy.Core.CSharp.CSharpDecompiler.RunTransformsAndGenerateCode(BuilderState& state, IDecompilerOutput output, DecompilationContext ctx, IAstTransform additionalTransform) in D:\a\dnSpyEx\dnSpyEx\Extensions\ILSpy.Decompiler\dnSpy.Decompiler.ILSpy.Core\CSharp\CSharpDecompiler.cs:line 245
   at dnSpy.Decompiler.ILSpy.Core.CSharp.CSharpDecompiler.Decompile(TypeDef type, IDecompilerOutput output, DecompilationContext ctx) in D:\a\dnSpyEx\dnSpyEx\Extensions\ILSpy.Decompiler\dnSpy.Decompiler.ILSpy.Core\CSharp\CSharpDecompiler.cs:line 236
   at dnSpy.Documents.Tabs.NodeDecompiler.Decompile(DocumentTreeNodeData node) in D:\a\dnSpyEx\dnSpyEx\dnSpy\dnSpy\Documents\Tabs\NodeDecompiler.cs:line 95
   at dnSpy.Documents.Tabs.DefaultDecompileNode.Decompile(IDecompileNodeContext context, DocumentTreeNodeData node) in D:\a\dnSpyEx\dnSpyEx\dnSpy\dnSpy\Documents\Tabs\DefaultDecompileNode.cs:line 28
   at dnSpy.Documents.Tabs.DocumentTreeNodeDecompiler.Decompile(IDecompileNodeContext decompileNodeContext, DocumentTreeNodeData[] nodes) in D:\a\dnSpyEx\dnSpyEx\dnSpy\dnSpy\Documents\Tabs\DocumentTreeNodeDecompiler.cs:line 61
   at dnSpy.Documents.Tabs.DocViewer.DecompileDocumentTabContent.CreateContentAsync(IAsyncShowContext ctx) in D:\a\dnSpyEx\dnSpyEx\dnSpy\dnSpy\Documents\Tabs\DocViewer\DecompileDocumentTabContent.cs:line 223
   at dnSpy.Documents.Tabs.TabContentImpl.<>c__DisplayClass51_0.<ShowInternal>b__0() in D:\a\dnSpyEx\dnSpyEx\dnSpy\dnSpy\Documents\Tabs\TabContentImpl.cs:line 345
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__271_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---`

**Comment by Maverick1983** [comment]
.zip
[_PersonalSTRING.zip](https://github.com/dnSpyEx/dnSpy/files/10011069/_PersonalSTRING.zip)

**Comment by ElektroKill** [comment]
I've pushed a fix for this bug which will be available in the next release of dnSpyEx.

If necessary, you can also download the preview build available here which contains this fix.
https://github.com/dnSpyEx/dnSpy/actions/runs/3473170859 (still building at the time of writing)
