### ISSUE TITLE
All methods failed to decompile

### ISSUE THREAD

**Issue by Yehh22** [dnSpyEx/dnSpy#330]
### dnSpyEx version

6.5.0 (69f8e3d)

### Describe the Bug

This is the first time I encounted a Unity game that fails to decompile on dnSpy. All methods can't be decompiled, it always throw this error

```
/*
An exception occurred when decompiling this method (06000949)

ICSharpCode.Decompiler.DecompilerException: Error decompiling System.Collections.Generic.List`1<System.String> Game.ConfigValidator::CheckGameData(Game.Model.GameData)
 ---> System.OverflowException: Array dimensions exceeded supported range.
   at ICSharpCode.Decompiler.ILAst.ILAstBuilder.StackSlot.ModifyStack(StackSlot[] stack, Int32 popCount, Int32 pushCount, ByteCode pushDefinition) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstBuilder.cs:line 50
   at ICSharpCode.Decompiler.ILAst.ILAstBuilder.StackAnalysis(MethodDef methodDef) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstBuilder.cs:line 403
   at ICSharpCode.Decompiler.ILAst.ILAstBuilder.Build(MethodDef methodDef, Boolean optimize, DecompilerContext context) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstBuilder.cs:line 278
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(IEnumerable`1 parameters, MethodDebugInfoBuilder& builder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 103
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, AutoPropertyProvider autoPropertyProvider, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, StringBuilder sb, MethodDebugInfoBuilder& stmtsBuilder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 88
   --- End of inner exception stack trace ---
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, AutoPropertyProvider autoPropertyProvider, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, StringBuilder sb, MethodDebugInfoBuilder& stmtsBuilder) in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 92
   at ICSharpCode.Decompiler.Ast.AstBuilder.<>c__DisplayClass90_0.<AddMethodBody>b__0() in D:\a\dnSpy\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstBuilder.cs:line 1672
*/;
```

### How To Reproduce

1. Open this file in dnSpy [0.zip](https://github.com/user-attachments/files/15902914/0.zip)
2. Open any methods or getter/setter methods

### Expected Behavior

Be able to decompile to C#

### Actual Behavior

See "Describe the Bug"

**Comment by ElektroKill** [comment]
Hello, the file you uploaded does not contain valid IL code in the method bodies. You can see this when you switch to the IL disassembler.
![image](https://github.com/dnSpyEx/dnSpy/assets/37494960/6a88519a-f5e4-4031-ac2f-c44b748e4f02)

The code in the assembly is obviously encrypted or protected in some way. In order to decompile, you will have to analyze the game and see what kind of protection is being employed in order to undo it and decompile the file. This is not something I can help you with as it is unrelated to dnSpy. dnSpy crashes since the code it is being fed is not valid.

Closing the issue as it is out of the scope of dnSpy.
