### ISSUE TITLE
ILAstBuilder stack inconsistency

### ISSUE THREAD

**Issue by stevemk14ebr** [dnSpyEx/dnSpy#38]
Before clicking `Submit new issue`, try the latest build [![](https://github.com/dnSpyEx/dnSpy/workflows/GitHub%20CI/badge.svg)](https://github.com/dnSpyEx/dnSpy/actions)

- What version did you use?
Current master branch built from source

- Write down all steps needed to reproduce this issue. Also attach any needed files.
Attached is a 7z archive with the password 'infected'. The contained file is malware, do not execute it, the .exe extension has been removed for safety. Open this file in dnSpy and navigate through the file, multiple functions will fail to decompile with a 'Inconsistent stack size at' in the file ICSharpCode.Decompiler.ILAst.ILAstBuilder.cs

This exposes a larger issue, which is that dnSpy still uses the ILAstBuilder from an old version of ILSpy. This appears to have been replaced with a 'new decompiler' in commit https://github.com/icsharpcode/ILSpy/commit/0cd8e21ff7cdbfa30875a669480c3c5474ac1d5d which deletes the file ILAstBuilder.cs. The last commit to contain this file is: https://github.com/icsharpcode/ILSpy/blob/19800c3b162dd003f88c3171861912f9e77f1f41/ICSharpCode.Decompiler/ILAst/ILAstBuilder.cs

Details:
```
// Token: 0x0600003A RID: 58 RVA: 0x000027C0 File Offset: 0x000009C0
public static IntPtr \u202A\u202D\u206A\u200B\u206A\u202D\u202E\u202C\u206C\u202C\u206E\u200D\u206C\u202B\u206F\u206A\u206A\u202E\u206F\u206C\u206A\u200E\u206C\u202A\u202B\u200E\u206B\u200F\u200B\u202B\u202C\u206F\u202E\u202C\u200E\u206A\u200D\u200B\u206F\u200D\u202E(string)
{
/*
An exception occurred when decompiling this method (0600003A)

ICSharpCode.Decompiler.DecompilerException: Error decompiling System.IntPtr ‌⁯‌‍‮‬‫⁫⁪‍‪⁭‭‏⁯‭‍‭‪⁯⁬⁫‏‎⁭‍⁬⁬‬‌⁯‌‭‍⁬⁯‌​‬⁯‮::‪‭⁪​⁪‭‮‬⁬‬⁮‍⁬‫⁯⁪⁪‮⁯⁬⁪‎⁬‪‫‎⁫‏​‫‬⁯‮‬‎⁪‍​⁯‍‮(System.String)
 ---> System.Exception: Inconsistent stack size at IL_D8
   at ICSharpCode.Decompiler.ILAst.ILAstBuilder.StackAnalysis(MethodDef methodDef) in C:\Users\steve\source\repos\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstBuilder.cs:line 443
   at ICSharpCode.Decompiler.ILAst.ILAstBuilder.Build(MethodDef methodDef, Boolean optimize, DecompilerContext context) in C:\Users\steve\source\repos\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstBuilder.cs:line 269
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(IEnumerable`1 parameters, MethodDebugInfoBuilder& builder) in C:\Users\steve\source\repos\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 112
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, AutoPropertyProvider autoPropertyProvider, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, StringBuilder sb, MethodDebugInfoBuilder& stmtsBuilder) in C:\Users\steve\source\repos\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 88
   --- End of inner exception stack trace ---
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, AutoPropertyProvider autoPropertyProvider, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, StringBuilder sb, MethodDebugInfoBuilder& stmtsBuilder) in C:\Users\steve\source\repos\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 92
   at ICSharpCode.Decompiler.Ast.AstBuilder.<>c__DisplayClass90_0.<AddMethodBody>b__0() in C:\Users\steve\source\repos\dnSpy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstBuilder.cs:line 1519
*/;
}
```

IL code:

<details>
  <summary>Spoiler: IL code</summary>

```
  // Token: 0x0600003A RID: 58 RVA: 0x000027C0 File Offset: 0x000009C0
.method public hidebysig static 
	native int '‪‭⁪​⁪‭‮‬⁬‬⁮‍⁬‫⁯⁪⁪‮⁯⁬⁪‎⁬‪‫‎⁫‏​‫‬⁯‮‬‎⁪‍​⁯‍‮' (
		string ''
	) cil managed 
{
	// Header Size: 12 bytes
	// Code Size: 347 (0x15B) bytes
	// LocalVarSig Token: 0x11000009 RID: 9
	.maxstack 4
	.locals init (
		[0] class [mscorlib]System.Collections.IEnumerator,
		[1] class [System]System.Diagnostics.ProcessModule,
		[2] native int,
		[3] class [mscorlib]System.IDisposable,
		[4] uint32
	)

	/* 0x000009CC 2841000006   */ IL_0000: call      class [System]System.Diagnostics.Process '‌⁯‌‍‮‬‫⁫⁪‍‪⁭‭‏⁯‭‍‭‪⁯⁬⁫‏‎⁭‍⁬⁬‬‌⁯‌‭‍⁬⁯‌​‬⁯‮'::'⁮‮⁭‌‍‍‪‬‭⁪​⁬‍⁮‏‭⁯‌‫⁯⁭⁯‌⁮⁯⁪⁪‪⁪‏⁫⁮‍⁭⁯⁭‫‪⁬‫‮$PST06000041'()
	/* 0x000009D1 2842000006   */ IL_0005: call      class [System]System.Diagnostics.ProcessModuleCollection '‌⁯‌‍‮‬‫⁫⁪‍‪⁭‭‏⁯‭‍‭‪⁯⁬⁫‏‎⁭‍⁬⁬‬‌⁯‌‭‍⁬⁯‌​‬⁯‮'::'‫‮‌‏⁬⁬⁮‍‬​‎‌‎⁯⁯⁮‪‬⁭⁪⁬​‎‬⁮​‮‪‏‏‎⁯‭‌‪⁮​⁮⁭‫‮$PST06000042'(class [System]System.Diagnostics.Process)
	/* 0x000009D6 2843000006   */ IL_000A: call      class [mscorlib]System.Collections.IEnumerator '‌⁯‌‍‮‬‫⁫⁪‍‪⁭‭‏⁯‭‍‭‪⁯⁬⁫‏‎⁭‍⁬⁬‬‌⁯‌‭‍⁬⁯‌​‬⁯‮'::'‬⁪‍‬​‮​‍‫​⁫‎⁬‫⁮⁯⁪‏⁭‬⁪‏​⁫‎‭‏⁫​⁫⁭⁮⁪‮‎‫⁮⁮⁪‬‮$PST06000043'(class [mscorlib]System.Collections.ReadOnlyCollectionBase)
	/* 0x000009DB 0A           */ IL_000F: stloc.0
	.try
	{
		/* 0x000009DC 38AB000000   */ IL_0010: br        IL_00C0

		/* 0x000009E1 2008D4990C   */ IL_0015: ldc.i4    211407880
		// loop start (head: IL_001A)
			/* 0x000009E6 2001B57E13   */ IL_001A: ldc.i4    327070977
			/* 0x000009EB 61           */ IL_001F: xor
			/* 0x000009EC 25           */ IL_0020: dup
			/* 0x000009ED 1304         */ IL_0021: stloc.s   V_4
			/* 0x000009EF 1C           */ IL_0023: ldc.i4.6
			/* 0x000009F0 5E           */ IL_0024: rem.un
			/* 0x000009F1 4506000000D3FFFFFF490000007E0000009F0000001E0000000A000000 */ IL_0025: switch    (IL_0015, IL_008B, IL_00C0, IL_00E1, IL_0060, IL_004C)

			/* 0x00000A0E 17           */ IL_0042: ldc.i4.1
			/* 0x00000A0F 2CD0         */ IL_0043: brfalse.s IL_0015

			/* 0x00000A11 3897000000   */ IL_0045: br        IL_00E1

			/* 0x00000A16 11FF         */ IL_004A: ldloc.s   <null>

			/* 0x00000A18 06           */ IL_004C: ldloc.0
			/* 0x00000A19 2844000006   */ IL_004D: call      object '‌⁯‌‍‮‬‫⁫⁪‍‪⁭‭‏⁯‭‍‭‪⁯⁬⁫‏‎⁭‍⁬⁬‬‌⁯‌‭‍⁬⁯‌​‬⁯‮'::'‎⁬‮‭‬‏‌⁮‫‏‭‭‎‏‫‍⁪‪‌⁪⁬‬⁮‫⁫‏‏‎‏⁬‭⁫⁭​‫‎⁪‏‪‬‮$PST06000044'(class [mscorlib]System.Collections.IEnumerator)
			/* 0x00000A1E 7416000001   */ IL_0052: castclass [System]System.Diagnostics.ProcessModule
			/* 0x00000A23 0B           */ IL_0057: stloc.1
			/* 0x00000A24 20408CE034   */ IL_0058: ldc.i4    887131200
			/* 0x00000A29 2BBB         */ IL_005D: br.s      IL_001A

			/* 0x00000A2B 25           */ IL_005F: dup
			// loop start (head: IL_0060)
				/* 0x00000A2C 07           */ IL_0060: ldloc.1
				/* 0x00000A2D 2848000006   */ IL_0061: call      native int '‌⁯‌‍‮‬‫⁫⁪‍‪⁭‭‏⁯‭‍‭‪⁯⁬⁫‏‎⁭‍⁬⁬‬‌⁯‌‭‍⁬⁯‌​‬⁯‮'::'⁫⁮‬‎‫⁭⁫‭‏⁭​⁫‌⁪⁮‫‮⁮‪‫‍⁬⁪‪⁪‌‭⁪⁬⁬‌‫‪⁯‪⁮‍⁭‪‪‮$PST06000048'(class [System]System.Diagnostics.ProcessModule)
				/* 0x00000A32 0C           */ IL_0066: stloc.2
				/* 0x00000A33 DDED000000   */ IL_0067: leave     IL_0159

				/* 0x00000A38 1104         */ IL_006C: ldloc.s   V_4
				/* 0x00000A3A 20BA0D0AF3   */ IL_006E: ldc.i4    -217444934
				/* 0x00000A3F 5A           */ IL_0073: mul
				/* 0x00000A40 208D1EE375   */ IL_0074: ldc.i4    1977818765
				/* 0x00000A45 61           */ IL_0079: xor
				/* 0x00000A46 D005000006   */ IL_007A: ldtoken   method string '‎‭‌‪‪‭⁪‏⁭​‍‫‏‪‌‫⁪‎‭⁯‭‭⁬‏⁬⁯⁮‌‬‎‍⁪⁮⁮‍‍‌‍‭⁪‮'::'‏‮‍​⁪‭⁭‭⁫‌⁮‍‎‎​​‪​​‎‭‎‍⁯⁫​⁮‫⁪⁭‌‎‌‍​⁯⁮‫⁬⁫‮'()
				/* 0x00000A4B 8C28000001   */ IL_007F: box       [mscorlib]System.RuntimeMethodHandle
				/* 0x00000A50 2CDA         */ IL_0084: brfalse.s IL_0060
			// end loop
			/* 0x00000A52 16           */ IL_0086: ldc.i4.0
			/* 0x00000A53 26           */ IL_0087: pop
			/* 0x00000A54 2B90         */ IL_0088: br.s      IL_001A

			/* 0x00000A56 26           */ IL_008A: pop

			/* 0x00000A57 07           */ IL_008B: ldloc.1
			/* 0x00000A58 2845000006   */ IL_008C: call      string '‌⁯‌‍‮‬‫⁫⁪‍‪⁭‭‏⁯‭‍‭‪⁯⁬⁫‏‎⁭‍⁬⁬‬‌⁯‌‭‍⁬⁯‌​‬⁯‮'::'‌⁬‫⁮‬⁬⁫‮​‫‏⁯⁭⁪‌‌‪⁭⁬‫‪⁫‌⁯⁪‎⁪‫‫⁭‌⁮‌⁬⁪‪⁫‍‬‬‮$PST06000045'(class [System]System.Diagnostics.ProcessModule)
			/* 0x00000A5D 2846000006   */ IL_0091: call      string '‌⁯‌‍‮‬‫⁫⁪‍‪⁭‭‏⁯‭‍‭‪⁯⁬⁫‏‎⁭‍⁬⁬‬‌⁯‌‭‍⁬⁯‌​‬⁯‮'::'‮‍⁪⁮‭‌⁬‫⁯‫‪‭⁫‭⁭‫⁬⁯⁭⁫⁪‮‬‪‬⁫‍‮⁯⁯⁭‬⁭⁮⁪‮⁮‮‮‬‮$PST06000046'(string)
			/* 0x00000A62 02           */ IL_0096: ldarg.0
			/* 0x00000A63 2846000006   */ IL_0097: call      string '‌⁯‌‍‮‬‫⁫⁪‍‪⁭‭‏⁯‭‍‭‪⁯⁬⁫‏‎⁭‍⁬⁬‬‌⁯‌‭‍⁬⁯‌​‬⁯‮'::'‮‍⁪⁮‭‌⁬‫⁯‫‪‭⁫‭⁭‫⁬⁯⁭⁫⁪‮‬‪‬⁫‍‮⁯⁯⁭‬⁭⁮⁪‮⁮‮‮‬‮$PST06000046'(string)
			/* 0x00000A68 2847000006   */ IL_009C: call      bool '‌⁯‌‍‮‬‫⁫⁪‍‪⁭‭‏⁯‭‍‭‪⁯⁬⁫‏‎⁭‍⁬⁬‬‌⁯‌‭‍⁬⁯‌​‬⁯‮'::'⁮⁫‌‫‭‍‭​​⁯⁫‬‮‌‍‮⁮‎‮‍‬⁫⁮‍‎⁭‌⁭⁪⁬‎‮⁬‮⁭‍‌‬⁬⁬‮$PST06000047'(string, string)
			/* 0x00000A6D 2D08         */ IL_00A1: brtrue.s  IL_00AB

			/* 0x00000A6F 208479EDBA   */ IL_00A3: ldc.i4    -1158841980
			/* 0x00000A74 25           */ IL_00A8: dup
			/* 0x00000A75 2B06         */ IL_00A9: br.s      IL_00B1

			/* 0x00000A77 20E03A4DBA   */ IL_00AB: ldc.i4    -1169343776
			/* 0x00000A7C 25           */ IL_00B0: dup

			/* 0x00000A7D 26           */ IL_00B1: pop
			/* 0x00000A7E 1104         */ IL_00B2: ldloc.s   V_4
			/* 0x00000A80 20399E4318   */ IL_00B4: ldc.i4    407084601
			/* 0x00000A85 5A           */ IL_00B9: mul
			/* 0x00000A86 61           */ IL_00BA: xor
			/* 0x00000A87 385AFFFFFF   */ IL_00BB: br        IL_001A
		// end loop
		// loop start (head: IL_00C0)
			/* 0x00000A8C 06           */ IL_00C0: ldloc.0
			/* 0x00000A8D 2849000006   */ IL_00C1: call      bool '‌⁯‌‍‮‬‫⁫⁪‍‪⁭‭‏⁯‭‍‭‪⁯⁬⁫‏‎⁭‍⁬⁬‬‌⁯‌‭‍⁬⁯‌​‬⁯‮'::'‎‬​⁫‏⁭‌⁪⁫‌⁪‪‌‏⁪‬‍‭⁭⁬⁭⁭​⁭​⁪⁭‫⁫⁪‌‪⁮⁬‌‍⁭⁫‪⁪‮$PST06000049'(class [mscorlib]System.Collections.IEnumerator)
			/* 0x00000A92 2C08         */ IL_00C6: brfalse.s IL_00D0

			/* 0x00000A94 2008D4990C   */ IL_00C8: ldc.i4    211407880
			/* 0x00000A99 25           */ IL_00CD: dup
			/* 0x00000A9A 2B06         */ IL_00CE: br.s      IL_00D6

			/* 0x00000A9C 20CA75476C   */ IL_00D0: ldc.i4    1816622538
			/* 0x00000AA1 25           */ IL_00D5: dup

			/* 0x00000AA2 26           */ IL_00D6: pop
			/* 0x00000AA3 17           */ IL_00D7: ldc.i4.1
			/* 0x00000AA4 2CE6         */ IL_00D8: brfalse.s IL_00C0
		// end loop
		/* 0x00000AA6 383BFFFFFF   */ IL_00DA: br        IL_001A

		/* 0x00000AAB 0EFF         */ IL_00DF: ldarg.s   <null>

		/* 0x00000AAD DE70         */ IL_00E1: leave.s   IL_0153
	} // end .try
	finally
	{
		/* 0x00000AAF 06           */ IL_00E3: ldloc.0
		/* 0x00000AB0 7507000001   */ IL_00E4: isinst    [mscorlib]System.IDisposable
		/* 0x00000AB5 0D           */ IL_00E9: stloc.3

		/* 0x00000AB6 20E4BDDB51   */ IL_00EA: ldc.i4    1373355492
		// loop start (head: IL_00EF)
			/* 0x00000ABB 2001B57E13   */ IL_00EF: ldc.i4    327070977
			/* 0x00000AC0 61           */ IL_00F4: xor
			/* 0x00000AC1 25           */ IL_00F5: dup
			/* 0x00000AC2 1304         */ IL_00F6: stloc.s   V_4
			/* 0x00000AC4 1A           */ IL_00F8: ldc.i4.4
			/* 0x00000AC5 5E           */ IL_00F9: rem.un
			/* 0x00000AC6 4504000000290000000700000043000000DBFFFFFF */ IL_00FA: switch    (IL_0138, IL_0116, IL_0152, IL_00EA)

			/* 0x00000ADB 17           */ IL_010F: ldc.i4.1
			/* 0x00000ADC 2CD8         */ IL_0110: brfalse.s IL_00EA

			/* 0x00000ADE 2B3E         */ IL_0112: br.s      IL_0152

			/* 0x00000AE0 0EFF         */ IL_0114: ldarg.s   <null>
			// loop start (head: IL_0116)
				/* 0x00000AE2 09           */ IL_0116: ldloc.3
				/* 0x00000AE3 2C08         */ IL_0117: brfalse.s IL_0121

				/* 0x00000AE5 20C0946FCA   */ IL_0119: ldc.i4    -898657088
				/* 0x00000AEA 25           */ IL_011E: dup
				/* 0x00000AEB 2B06         */ IL_011F: br.s      IL_0127

				/* 0x00000AED 2092F723A0   */ IL_0121: ldc.i4    -1608255598
				/* 0x00000AF2 25           */ IL_0126: dup

				/* 0x00000AF3 26           */ IL_0127: pop
				/* 0x00000AF4 1104         */ IL_0128: ldloc.s   V_4
				/* 0x00000AF6 20D5444BDC   */ IL_012A: ldc.i4    -599046955
				/* 0x00000AFB 5A           */ IL_012F: mul
				/* 0x00000AFC 61           */ IL_0130: xor
				/* 0x00000AFD 16           */ IL_0131: ldc.i4.0
				/* 0x00000AFE 2DE2         */ IL_0132: brtrue.s  IL_0116
			// end loop
			/* 0x00000B00 2BB9         */ IL_0134: br.s      IL_00EF

			/* 0x00000B02 11FF         */ IL_0136: ldloc.s   <null>
			// loop start (head: IL_0138)
				/* 0x00000B04 09           */ IL_0138: ldloc.3
				/* 0x00000B05 284A000006   */ IL_0139: call      void '‌⁯‌‍‮‬‫⁫⁪‍‪⁭‭‏⁯‭‍‭‪⁯⁬⁫‏‎⁭‍⁬⁬‬‌⁯‌‭‍⁬⁯‌​‬⁯‮'::'⁫​‌‎‫‎‏⁬​⁫​⁭‏⁯⁪⁪‍⁬‏‫‍⁭​⁮‏‫‎‮‍‮⁭‌‭‍⁫⁬‬⁫⁮‬‮$PST0600004A'(class [mscorlib]System.IDisposable)
				/* 0x00000B0A 1104         */ IL_013E: ldloc.s   V_4
				/* 0x00000B0C 20E968E190   */ IL_0140: ldc.i4    -1864275735
				/* 0x00000B11 5A           */ IL_0145: mul
				/* 0x00000B12 2093D9B470   */ IL_0146: ldc.i4    1890900371
				/* 0x00000B17 61           */ IL_014B: xor
				/* 0x00000B18 17           */ IL_014C: ldc.i4.1
				/* 0x00000B19 2CE9         */ IL_014D: brfalse.s IL_0138
			// end loop
			/* 0x00000B1B 2B9E         */ IL_014F: br.s      IL_00EF
		// end loop
		/* 0x00000B1D 7A           */ IL_0151: throw

		/* 0x00000B1E DC           */ IL_0152: endfinally
	} // end handler

	/* 0x00000B1F 7E0B00000A   */ IL_0153: ldsfld    native int [mscorlib]System.IntPtr::Zero
	/* 0x00000B24 2A           */ IL_0158: ret

	/* 0x00000B25 08           */ IL_0159: ldloc.2
	/* 0x00000B26 2A           */ IL_015A: ret
} // end of method '‌⁯‌‍‮‬‫⁫⁪‍‪⁭‭‏⁯‭‍‭‪⁯⁬⁫‏‎⁭‍⁬⁬‬‌⁯‌‭‍⁬⁯‌​‬⁯‮'::'‪‭⁪​⁪‭‮‬⁬‬⁮‍⁬‫⁯⁪⁪‮⁯⁬⁪‎⁬‪‫‎⁫‏​‫‬⁯‮‬‎⁪‍​⁯‍‮'
  ```
</details>

**Comment by ElektroKill** [comment]
Hi, dnSpy does use a rather archaic version of ILSpy (2.4). This causes many issues and the one you are experiencing is partially caused by that. The old ILSpy 2.4 code isn't very good at recovering from errors compared to the later versions. However, the sample you provided is protected with ConfuserEx which has a specific built-in measure to counter decompiler engines. It does so by creating weird branches and instruction patterns that confuse the decompiler's stack analyzer. in ILSpy 2.4 this results in a crash but in ILSpy 7.1 (latest) it generates invalid code.

I'm working on updating dnSpy to use the ILSpy 7.1 engine (see https://github.com/dnSpyEx/dnSpy/tree/feature/new-ilspy), but there is still a lot more work to do.

As for creating correct decompilation from this IL code: You can try reporting the issue to the ILSpy dev team but I don't know if they will fix it as they are not interested in supporting obfuscated binaries. If however, ILSpy does fix it, it will be part of dnSpy 7.0 which will include the latest ILSpy engine. I sadly won't be able to fix this in the current ILSpy 2.4 decompiler as it would probably require quite a few changes and I'd rather spend time getting the new engine running properly under dnSpy :/

Incorrect decompilation of 7.1:
We see ILSpy uses a discard instead of assigning it to the proper `num2` local.
![image](https://user-images.githubusercontent.com/37494960/137491604-0359b6e4-c71e-4133-9310-4c20377a92a7.png)

I'm going to leave this issue open for now in case someone else would like to have a look at it. Sadly, as I mentioned, this won't be resolved soon :/
